### ISSUE TITLE
Gestion des dates négatives et des evènements avec date début/fin

### ISSUE THREAD

**Issue by VSasyan** [VSasyan/Octo#1]
## Date de fin

Premièrement il faudrait ajouter un date_fin (on aurait donc date_maj, date_debut, date_fin).
#### MySQL

J'ai regardé sur internet, MySQL ne semble pas gérer les dates BC :
http://stackoverflow.com/questions/18654781/how-to-store-very-old-dates-in-database
#### PostgreSQL

Ca semble marcher avec postgre :
http://www.postgresql.org/docs/9.4/static/datatype-datetime.html
#### Solution pratique ?

Apres peut-etre est-ce plus simple de créer 3 champs (annee, mois, jour). Le défaut de cette solution c'est que c'est lourd puisqu'il faut aussi stocker la date de fin.

Ca donnerait : date_maj, date_debut_année, date_debut_mois, ...
**Ou en plus court :
date_maj, debut_annee, debut_mois, debut_jour, fin_annee, fin_mois, fin_jour**

**Comment by Nerisson** [comment]
Ok pour la date fin. Je propose dans un premier temps de partir avec la solution bourrin et plus pratique, je vais essayer d'encapsuler au mieux pour que ce soit changeable.
